version: '3.8'

services:
  registration-service:
    build: ./Registration Module
    ports:
      - "3001:3000"  # Expose the registration service on port 3001
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  message-service:
    build: ./Message Sending Module
    ports:
      - "3002:3000"  # Expose the message service on port 3002
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  notifications-service:
    build: ./Notifications Module
    ports:
      - "3003:3000"  # Expose the notification service on port 3003
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  user-settings-service:
    build: ./User Settings
    ports:
      - "3004:3000"  # Expose the user settings service on port 3004
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
